#!/usr/bin/env bash
set -eo pipefail

USER_HOME=$(eval echo "~${SUDO_USER:-$USER}")
CONTAINERS="$USER_HOME/Applications/containers"

does_it_exist() {
  docker inspect netbird-client &>/dev/null
  echo "$?"
}

install() {
  [[ $(does_it_exist) -eq 1 ]] || { echo 'Container netbird-client already exists. Check status with `netbird status`' >&2; exit 1; }
  # Create our installation directory
  mkdir -p "$CONTAINERS/netbird-client"

  # Prompt user for authentication key.
  echo -e "\nYou can create a one-time setup key at: https://app.netbird.io/setup-key\n"
  echo -n "Please enter your netbird setup key: "
  read -rs setup_key

  export NB_SETUP_KEY="$setup_key"

  echo -ne "\n\nPlease enter your desired hostname: "
  read -r hostname

  # Create docker-compose.yml
  cat > $CONTAINERS/netbird-client/docker-compose.yml << EOF
services:
  netbird-client:
      container_name: netbird-client
      hostname: $hostname
      restart: unless-stopped
      cap_add:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
      devices:
          # Required when using userspace mode or when kernel module is not available
          - /dev/net/tun
      network_mode: host
      environment:
          - NB_SETUP_KEY
          - NB_ENABLE_ROSENPASS=true
          - NB_ROSENPASS_PERMISSIVE=true
          - NB_ALLOW_SERVER_SSH=true
          - NB_DISABLE_SSH_AUTH=true
          - NB_WG_PORT=51821
      volumes:
          - netbird-client:/var/lib/netbird
      image: netbirdio/netbird:latest
volumes:
  netbird-client:
      name: netbird-client
EOF

  # Compose up
  cd "$CONTAINERS/netbird-client"
  echo "Starting Netbird..."
  docker compose up -d && echo -e "\nSuccess!\n"

  echo '`netbird status -d` -> Check status of netbird network & this peer'
  return 0
}


uninstall() {
  [[ $(does_it_exist) -eq 0 ]] || { echo 'Container netbird-client does not exist. Netbird is not installed.' >&2; exit 1; }
  read -rp "Are you sure you want to uninstall netbird? This is destructive. You will have to add a new peer to restore functionality. [Y/n] " confirm
  [[ "${confirm,,}" == "n" ]] && exit 0
  
  cd "$CONTAINERS/netbird-client"
  docker compose down --volumes --rmi all && echo "Uninstalled netbird."
  return 0
}

case "$1" in
  install) install;;
  uninstall) uninstall;;
  *) echo 'Please specify `install` or `uninstall`' && exit 1
esac
