#!/usr/bin/env bash
set -eo pipefail
# Intended for use with an ansible playbook
# Requires setting the following environment variables in the relevant task:
# - NB_SETUP_KEY (netbird setup key)
# - NB_HOSTNAME (netbird hostname)

USER_HOME=$(eval echo "~${SUDO_USER:-$USER}")
CONTAINERS="$USER_HOME/Applications/containers"

does_it_exist() {
  podman inspect netbird-client &>/dev/null
  echo "$?"
}

install() {
  [[ $(does_it_exist) -eq 1 ]] || { echo 'Container netbird-client already exists. Check status with `netbird status`' >&2; exit 1; }
  # Create our installation directory
  mkdir -p "$CONTAINERS/netbird-client"

  # Create compose.yml
  cat > $CONTAINERS/netbird-client/compose.yml << EOF
services:
  netbird-client:
      container_name: netbird-client
      hostname: $NB_HOSTNAME
      restart: unless-stopped
      cap_add:
          - NET_RAW
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
      devices:
          # Required when using userspace mode or when kernel module is not available
          - /dev/net/tun
      network_mode: host
      environment:
          - NB_SETUP_KEY
          - NB_ENABLE_ROSENPASS=true
          - NB_ROSENPASS_PERMISSIVE=true
          - NB_ALLOW_SERVER_SSH=true
          - NB_DISABLE_SSH_AUTH=true
          - NB_WG_PORT=51821
          - NB_DNS_RESOLVER_ADDRESS=127.0.0.1:53
      volumes:
          - netbird-client:/var/lib/netbird
      image: netbirdio/netbird:latest
volumes:
  netbird-client:
      name: netbird-client
EOF

  # Compose up
  cd "$CONTAINERS/netbird-client"
  echo "Starting Netbird with podman compose up..."
  sudo podman compose up -d && echo -e "\nSuccess!\n"

  echo '`netbird status -d` -> Check status of netbird network & this peer'
  return 0
}


uninstall() {
  [[ $(does_it_exist) -eq 0 ]] || { echo 'Container netbird-client does not exist. Netbird is not installed.' >&2; exit 1; }
  
  cd "$CONTAINERS/netbird-client"
  sudo podman compose down --volumes --rmi all && echo "Uninstalled netbird."
  return 0
}

case "$1" in
  install) install;;
  uninstall) uninstall;;
  *) echo 'Please specify `install` or `uninstall`' && exit 1
esac
