#!/usr/bin/env bash

rm "$USER_HOME/.config/environment.d/10-path.conf"
ln -s -v "$USER_HOME/.local/share/omarchy-overrides/systemd/environment.d/10-path.conf" "$USER_HOME/.config/environment.d/10-path.conf"

rm "$USER_HOME/.config/environment.d/telemetry.conf"
ln -s -v "$USER_HOME/.local/share/omarchy-overrides/systemd/environment.d/telemetry.conf" "$USER_HOME/.config/environment.d/telemetry.conf"
