-- lua/plugins/mason.lua
return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "ansible-language-server",
      "ansible-lint",
      "bash-language-server",
      "powershell-editor-services",
      "systemd-lsp",
      "markdown-oxide",
      "yaml-language-server",
      "helm-ls",
      "tofu-ls",
      "gopls",
      "golangci-lint-langserver",
      "ruby-lsp",
      "eslint-lsp",
      "basedpyright",
      "phpactor",
      "awk-language-server",
      "docker-language-server",
      "docker-compose-language-service",
      "graphql-language-service-cli",
      "html-lsp",
      "java-language-server",
      "jinja-lsp",
      "lua-language-server",
      "postgres-language-server",
      "puppet-editor-services",
      "sqlls",
      "basics-language-server",
    },
  },
}
